name: VoucherPlugin
version: '1.0-SNAPSHOT'
main: com.wtd.plugins.voucher.Voucher
api-version: 1.19
authors: [ Hill ]
description: voucher plugin
commands:
  voucher:
    description: Gives you a voucher